services:
  dbsender:
    image: dbsender
    environment:
      -  BOT_API_TOKEN=${{ secrets.BOT_API_TOKEN }}
      -  CHAT_ID=${{ secrets.CHAT_ID }}
      -  SERVER0_API=${{ secrets.SERVER0_API }}
      -  SERVER0_USERNAME=${{ secrets.SERVER0_USERNAME }}
      -  SERVER0_PASSWORD=${{ secrets.SERVER0_PASSWORD }}
      -  SERVER0_CAPTION=${{ secrets.SERVER0_CAPTION }}